version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/cli
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - cli

  - package-ecosystem: npm
    directory: /apps/vsc-plugin
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - vsc-plugin

  - package-ecosystem: gradle
    directory: /apps/jetbrains-plugin
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - jetbrains-plugin

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ci
