/**
 * Claude `/clear` + `/rename` follow-through for the baton (owner report
 * 2026-08-18: after `/clear` + `/rename` in the native TUI the mobile went
 * silent). The record shapes below are copied from a live claude 2.1.235
 * transcript captured on 2026-08-19 (see the integration test for the real
 * binary run).
 */
import { describe, it, expect } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, appendFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
  encodeCwd,
  parseHistoryFile,
  isLocalCommandEcho,
  isClearedConversationFile,
  watchConversationSwitch,
} from '../../src/agents/claude/history';

const CLEAR_ECHO =
  '<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>';
const RENAME_ECHO =
  '<command-name>/rename</command-name>\n            <command-message>rename</command-message>\n            <command-args>foo-renamed</command-args>';

function rec(type: string, extra: Record<string, unknown>): string {
  return JSON.stringify({ type, sessionId: 'new-id', uuid: `u-${Math.random()}`, timestamp: '2026-08-19T14:32:32.222Z', ...extra });
}
function userRec(text: string, isMeta = false): string {
  return rec('user', { isMeta, message: { role: 'user', content: text } });
}
function assistantRec(text: string): string {
  return rec('assistant', { message: { role: 'assistant', model: 'claude-x', content: [{ type: 'text', text }] } });
}

/** The records claude writes the instant `/clear` runs (before any turn). */
function clearedFileLines(): string[] {
  return [
    rec('mode', { mode: 'normal' }),
    userRec('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>', true),
    userRec(CLEAR_ECHO),
    rec('system', { subtype: 'local_command', content: '<local-command-stdout></local-command-stdout>', isMeta: true }),
  ];
}
/** `/rename foo-renamed` appends these to the CURRENT file — no new conversation. */
function renameLines(): string[] {
  return [
    rec('custom-title', { customTitle: 'foo-renamed' }),
    rec('agent-name', { agentName: 'foo-renamed' }),
    rec('system', { subtype: 'local_command', content: RENAME_ECHO, isMeta: true }),
    rec('system', { subtype: 'local_command', content: '<local-command-stdout>Session renamed to: foo-renamed</local-command-stdout>', isMeta: true }),
    userRec('<system-reminder>\nThe user named this session "foo-renamed".\n</system-reminder>', true),
  ];
}

async function waitUntil(pred: () => boolean, ms = 4_000): Promise<void> {
  const deadline = Date.now() + ms;
  while (Date.now() < deadline) {
    if (pred()) return;
    await new Promise((r) => setTimeout(r, 25));
  }
  throw new Error('timed out');
}

describe('claude/history — local slash-command echoes', () => {
  it('isLocalCommandEcho recognises <command-name> / <local-command-*> wrappers only', () => {
    expect(isLocalCommandEcho(CLEAR_ECHO)).toBe(true);
    expect(isLocalCommandEcho(RENAME_ECHO)).toBe(true);
    expect(isLocalCommandEcho('<local-command-stdout>x</local-command-stdout>')).toBe(true);
    expect(isLocalCommandEcho('Reply with the single word TWO.')).toBe(false);
    expect(isLocalCommandEcho('please run /clear for me')).toBe(false);
  });

  it('parseHistoryFile drops the /clear + /rename echoes but keeps the real turns around them', () => {
    const dir = mkdtempSync(path.join(tmpdir(), 'claude-h-switch-'));
    const file = path.join(dir, 'new-id.jsonl');
    writeFileSync(
      file,
      [
        ...clearedFileLines(),
        ...renameLines(),
        userRec('Reply with the single word TWO.'),
        rec('last-prompt', { lastPrompt: 'Reply with the single word TWO.' }),
        rec('custom-title', { customTitle: 'foo-renamed' }),
        assistantRec('TWO'),
      ].join('\n') + '\n',
    );
    const msgs = parseHistoryFile(file);
    expect(msgs.map((m) => [m.role, m.text])).toEqual([
      ['user', 'Reply with the single word TWO.'],
      ['agent', 'TWO'],
    ]);
    rmSync(dir, { recursive: true, force: true });
  });
});

describe('claude/history — isClearedConversationFile', () => {
  it('is true for a transcript that opens with the /clear echo', () => {
    const dir = mkdtempSync(path.join(tmpdir(), 'claude-h-switch-'));
    const file = path.join(dir, 'a.jsonl');
    writeFileSync(file, clearedFileLines().join('\n') + '\n');
    expect(isClearedConversationFile(file)).toBe(true);
    rmSync(dir, { recursive: true, force: true });
  });

  it('is true for a SessionStart:clear hook attachment (hooks configured, no echo yet)', () => {
    const dir = mkdtempSync(path.join(tmpdir(), 'claude-h-switch-'));
    const file = path.join(dir, 'a.jsonl');
    writeFileSync(
      file,
      rec('attachment', { attachment: { type: 'hook_success', hookName: 'SessionStart:clear', content: 'x' } }) + '\n',
    );
    expect(isClearedConversationFile(file)).toBe(true);
    rmSync(dir, { recursive: true, force: true });
  });

  it('is false for a one-shot / ACP transcript (a plain user turn), the startup hook, and a missing file', () => {
    const dir = mkdtempSync(path.join(tmpdir(), 'claude-h-switch-'));
    const oneShot = path.join(dir, 'oneshot.jsonl');
    writeFileSync(oneShot, [userRec('detect the dev server for this repo'), assistantRec('{"framework":"next"}')].join('\n') + '\n');
    expect(isClearedConversationFile(oneShot)).toBe(false);
    const startup = path.join(dir, 'startup.jsonl');
    writeFileSync(startup, rec('attachment', { attachment: { type: 'hook_success', hookName: 'SessionStart:startup', content: 'x' } }) + '\n');
    expect(isClearedConversationFile(startup)).toBe(false);
    // Mentioning /clear in a prompt is not a clear.
    const chat = path.join(dir, 'chat.jsonl');
    writeFileSync(chat, userRec('what does <command-name>/clear</command-name> do?') + '\n');
    expect(isClearedConversationFile(chat)).toBe(false);
    expect(isClearedConversationFile(path.join(dir, 'nope.jsonl'))).toBe(false);
    rmSync(dir, { recursive: true, force: true });
  });
});

describe('claude/history — watchConversationSwitch (event-driven)', () => {
  /** What claude appends to a file the instant it is /resume'd (both the
   *  explicit `/resume <id>` and the picker — verified live). */
  const resumeMarker = (): string => rec('last-prompt', { lastPrompt: 'Reply with the single word ONE.' }) + '\n';

  it('fires {kind:new} when /clear writes a fresh JSONL into an existing project dir, ignores one-shots + /rename, follows a second /clear', async () => {
    const root = mkdtempSync(path.join(tmpdir(), 'claude-h-switch-root-'));
    const cwd = '/Users/alice/work';
    const dir = path.join(root, encodeCwd(cwd));
    mkdirSync(dir, { recursive: true });
    const current = path.join(dir, 'current.jsonl');
    writeFileSync(current, userRec('hello') + '\n');
    const seen: Array<[string, string]> = [];
    const unwatch = watchConversationSwitch(cwd, { currentId: 'current' }, (id, info) => seen.push([id, info.kind]), root);
    try {
      // A `claude -p` one-shot in the same cwd (preview detection / AI summary)
      // lands in the same dir — it must NOT hijack the baton, even as it grows.
      const oneShot = path.join(dir, 'oneshot.jsonl');
      writeFileSync(oneShot, userRec('detect') + '\n');
      await new Promise((r) => setTimeout(r, 100));
      appendFileSync(oneShot, assistantRec('x') + '\n' + rec('last-prompt', { lastPrompt: 'detect' }) + '\n');
      // /rename on the current conversation — no switch either.
      appendFileSync(current, renameLines().join('\n') + '\n');
      await new Promise((r) => setTimeout(r, 300));
      expect(seen).toEqual([]);

      // /clear → new file, written the way claude does it: created, then the
      // echo appended a moment later.
      const next = path.join(dir, 'next-1.jsonl');
      writeFileSync(next, rec('mode', { mode: 'normal' }) + '\n');
      await new Promise((r) => setTimeout(r, 100));
      appendFileSync(next, clearedFileLines().slice(1).join('\n') + '\n');
      await waitUntil(() => seen.length === 1);
      expect(seen).toEqual([['next-1', 'new']]);

      // A turn on the new conversation is not another switch…
      appendFileSync(next, [userRec('TWO?'), assistantRec('TWO'), rec('last-prompt', { lastPrompt: 'TWO?' })].join('\n') + '\n');
      await new Promise((r) => setTimeout(r, 300));
      expect(seen).toEqual([['next-1', 'new']]);

      // …but a second /clear is.
      writeFileSync(path.join(dir, 'next-2.jsonl'), clearedFileLines().join('\n') + '\n');
      await waitUntil(() => seen.length === 2);
      expect(seen).toEqual([['next-1', 'new'], ['next-2', 'new']]);
    } finally {
      unwatch();
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fires {kind:resumed} when a KNOWN non-current transcript grows with the resume marker: a pre-existing one, and the one we /clear-ed away from', async () => {
    const root = mkdtempSync(path.join(tmpdir(), 'claude-h-switch-root-'));
    const cwd = '/Users/alice/work';
    const dir = path.join(root, encodeCwd(cwd));
    mkdirSync(dir, { recursive: true });
    const current = path.join(dir, 'current.jsonl');
    writeFileSync(current, [userRec('hello'), assistantRec('hi')].join('\n') + '\n');
    // An older conversation of this cwd from a previous day.
    const older = path.join(dir, 'older.jsonl');
    writeFileSync(older, [userRec('old question'), assistantRec('old answer')].join('\n') + '\n');
    const seen: Array<[string, string]> = [];
    const unwatch = watchConversationSwitch(cwd, { currentId: 'current' }, (id, info) => seen.push([id, info.kind]), root);
    try {
      // Growth WITHOUT the marker (e.g. a stray rename record) is not a resume.
      appendFileSync(older, rec('custom-title', { customTitle: 'x' }) + '\n');
      await new Promise((r) => setTimeout(r, 300));
      expect(seen).toEqual([]);

      // `/resume older` → claude appends the last-prompt record to older.jsonl.
      appendFileSync(older, resumeMarker());
      await waitUntil(() => seen.length === 1);
      expect(seen).toEqual([['older', 'resumed']]);

      // Turns on the resumed conversation (now current) are not switches.
      appendFileSync(older, [userRec('more'), assistantRec('sure'), rec('last-prompt', { lastPrompt: 'more' })].join('\n') + '\n');
      await new Promise((r) => setTimeout(r, 300));
      expect(seen).toEqual([['older', 'resumed']]);

      // `/resume current` — back to the conversation we left: it was baselined
      // when we switched away, so its growth is a resume too.
      appendFileSync(current, resumeMarker());
      await waitUntil(() => seen.length === 2);
      expect(seen).toEqual([['older', 'resumed'], ['current', 'resumed']]);

      // /clear then /resume the cleared-away conversation: round-trips.
      writeFileSync(path.join(dir, 'fresh.jsonl'), clearedFileLines().join('\n') + '\n');
      await waitUntil(() => seen.length === 3);
      expect(seen[2]).toEqual(['fresh', 'new']);
      appendFileSync(current, resumeMarker());
      await waitUntil(() => seen.length === 4);
      expect(seen[3]).toEqual(['current', 'resumed']);
    } finally {
      unwatch();
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('catches a /clear that CREATES the project dir (no turn before it)', async () => {
    const root = mkdtempSync(path.join(tmpdir(), 'claude-h-switch-root-'));
    const cwd = '/Users/alice/fresh';
    const dir = path.join(root, encodeCwd(cwd));
    const seen: string[] = [];
    // Project dir does not exist yet → the watcher must hang off the root.
    const unwatch = watchConversationSwitch(cwd, { currentId: 'premint' }, (id) => seen.push(id), root);
    try {
      await new Promise((r) => setTimeout(r, 100));
      mkdirSync(dir, { recursive: true });
      writeFileSync(path.join(dir, 'after-clear.jsonl'), clearedFileLines().join('\n') + '\n');
      await waitUntil(() => seen.length === 1);
      expect(seen).toEqual(['after-clear']);
    } finally {
      unwatch();
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('unsubscribe stops delivery', async () => {
    const root = mkdtempSync(path.join(tmpdir(), 'claude-h-switch-root-'));
    const cwd = '/Users/alice/work';
    const dir = path.join(root, encodeCwd(cwd));
    mkdirSync(dir, { recursive: true });
    const seen: string[] = [];
    const unwatch = watchConversationSwitch(cwd, { currentId: 'current' }, (id) => seen.push(id), root);
    unwatch();
    writeFileSync(path.join(dir, 'next.jsonl'), clearedFileLines().join('\n') + '\n');
    await new Promise((r) => setTimeout(r, 300));
    expect(seen).toEqual([]);
    rmSync(root, { recursive: true, force: true });
  });
});
