import { promises as fs } from 'fs';
import path from 'path';
import { log } from '../logger';
import { runSetupCommand } from './run-setup';

/**
 * Auto-provision a project's runtime dependencies (Postgres, Redis, …) inside
 * a codespace so its dev server boots on the first preview without manual
 * setup. See docs/superpowers/specs/2026-06-12-codespace-auto-provision-
 * project-deps-design.md.
 *
 * Strategy (per repo): compose-first → heuristic generation → `.env` → best-
 * effort migrations. Strictly best-effort + non-fatal — any failure degrades
 * to the preview error-UX (`preview_failed`), never blocks pairing or the
 * agent. Invoked fire-and-forget from the codespace bootstrap.
 */

const COMPOSE_FILES = [
  'docker-compose.yml',
  'docker-compose.yaml',
  'compose.yaml',
  'compose.yml',
];
const ENV_SAMPLES = ['.env.example', '.env.sample', '.env.local.example', '.env.template'];

interface ServiceSpec {
  name: string;
  image: string;
  port: number;
  environment: Record<string, string>;
  /** Compose healthcheck test argv, so `up -d --wait` blocks until ready. */
  healthTest: string[];
  /** Lines appended to a generated `.env` (connection strings → localhost). */
  envLines: string[];
}

const POSTGRES: ServiceSpec = {
  name: 'postgres',
  image: 'postgres:16',
  port: 5432,
  environment: { POSTGRES_USER: 'postgres', POSTGRES_PASSWORD: 'postgres', POSTGRES_DB: 'app' },
  healthTest: ['CMD-SHELL', 'pg_isready -U postgres'],
  envLines: [
    'DATABASE_URL=postgresql://postgres:postgres@localhost:5432/app',
    'DB_HOST=localhost',
    'DB_PORT=5432',
    'DB_USERNAME=postgres',
    'DB_PASSWORD=postgres',
    'DB_NAME=app',
  ],
};
const MYSQL: ServiceSpec = {
  name: 'mysql',
  image: 'mysql:8',
  port: 3306,
  environment: { MYSQL_ROOT_PASSWORD: 'mysql', MYSQL_DATABASE: 'app' },
  healthTest: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-pmysql'],
  envLines: ['DATABASE_URL=mysql://root:mysql@localhost:3306/app'],
};
const MONGO: ServiceSpec = {
  name: 'mongo',
  image: 'mongo:7',
  port: 27017,
  environment: {},
  healthTest: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")'],
  envLines: ['MONGODB_URI=mongodb://localhost:27017/app', 'MONGO_URL=mongodb://localhost:27017/app'],
};
const REDIS: ServiceSpec = {
  name: 'redis',
  image: 'redis:7',
  port: 6379,
  environment: {},
  healthTest: ['CMD', 'redis-cli', 'ping'],
  envLines: ['REDIS_URL=redis://localhost:6379', 'REDIS_HOST=localhost', 'REDIS_PORT=6379'],
};

/**
 * Map a project's package.json dependencies to the backing services it needs.
 * Pure + exported for tests. De-dupes (one service even if several drivers
 * pull it in) and is conservative (only well-known drivers).
 */
export function detectServicesFromDeps(pkg: {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}): ServiceSpec[] {
  const deps = new Set([
    ...Object.keys(pkg.dependencies ?? {}),
    ...Object.keys(pkg.devDependencies ?? {}),
  ]);
  const has = (...names: string[]): boolean => names.some((n) => deps.has(n));
  const out: ServiceSpec[] = [];
  if (has('pg', 'typeorm', '@nestjs/typeorm', 'sequelize', 'postgres', 'postgres.js', 'pg-promise'))
    out.push(POSTGRES);
  if (has('mysql', 'mysql2')) out.push(MYSQL);
  if (has('mongoose', 'mongodb')) out.push(MONGO);
  if (has('ioredis', 'redis', 'cache-manager-ioredis-yet', 'cache-manager-redis-store'))
    out.push(REDIS);
  return out;
}

/** Render a minimal, healthcheck'd compose file for the detected services. */
export function renderComposeYaml(services: ServiceSpec[]): string {
  const blocks = services.map((s) => {
    const env = Object.entries(s.environment);
    const envYaml = env.length
      ? '    environment:\n' + env.map(([k, v]) => `      ${k}: "${v}"`).join('\n') + '\n'
      : '';
    const health = JSON.stringify(s.healthTest);
    return (
      `  ${s.name}:\n` +
      `    image: ${s.image}\n` +
      `    restart: unless-stopped\n` +
      `    ports:\n      - "${s.port}:${s.port}"\n` +
      envYaml +
      `    healthcheck:\n` +
      `      test: ${health}\n` +
      `      interval: 5s\n      timeout: 3s\n      retries: 12\n`
    );
  });
  return `# Generated by codeam — auto-provisioned project dependencies.\n` +
    `# Do not edit; regenerated on each provision. See .codeam/provision/.\n` +
    `services:\n${blocks.join('')}`;
}

/** First migration npm-script that RUNS (not generates) migrations, or null. */
export function pickMigrationScript(scripts: Record<string, string>): string | null {
  const preferred = [
    'migration:run',
    'db:migrate',
    'migrate:deploy',
    'migrate:latest',
    'migrate:up',
    'prisma:migrate',
    'migrate',
  ];
  for (const k of preferred) if (scripts[k]) return k;
  // Fallback: any "*migrat*" script that clearly RUNS migrations and is not a
  // generate/create/rollback/down command.
  for (const k of Object.keys(scripts)) {
    if (
      /migrat/i.test(k) &&
      /(run|deploy|latest|up)/i.test(k) &&
      !/(generate|create|revert|rollback|undo|down|reset|drop)/i.test(k)
    ) {
      return k;
    }
  }
  return null;
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function firstExisting(cwd: string, names: string[]): Promise<string | null> {
  for (const n of names) if (await exists(path.join(cwd, n))) return n;
  return null;
}

/** Write `.env` from a sample (preferred) or generated lines. Never overwrites. */
async function ensureEnvFile(cwd: string, generated: ServiceSpec[]): Promise<void> {
  if (await exists(path.join(cwd, '.env'))) {
    log.info('provision', '.env already present — leaving it untouched');
    return;
  }
  const sample = await firstExisting(cwd, ENV_SAMPLES);
  if (sample) {
    const body = await fs.readFile(path.join(cwd, sample), 'utf8');
    await fs.writeFile(path.join(cwd, '.env'), body);
    log.info('provision', `wrote .env from ${sample}`);
    return;
  }
  if (generated.length > 0) {
    const body =
      '# Generated by codeam — points at the auto-provisioned local services.\n' +
      generated.flatMap((s) => s.envLines).join('\n') +
      '\n';
    await fs.writeFile(path.join(cwd, '.env'), body);
    log.info('provision', `generated .env for ${generated.map((s) => s.name).join('+')}`);
  }
}

async function readPackageJson(
  cwd: string,
): Promise<{ dependencies?: Record<string, string>; devDependencies?: Record<string, string>; scripts?: Record<string, string> } | null> {
  try {
    return JSON.parse(await fs.readFile(path.join(cwd, 'package.json'), 'utf8'));
  } catch {
    return null;
  }
}

async function runMigrationsIfPresent(cwd: string, scripts: Record<string, string>): Promise<void> {
  const script = pickMigrationScript(scripts);
  if (!script) return;
  log.info('provision', `running migrations: npm run ${script}`);
  const res = await runSetupCommand('npm', ['run', script], cwd, undefined, { timeoutMs: 120_000 });
  if (res.status !== 'ok') log.warn('provision', `migration script "${script}" → ${res.status} (non-fatal)`);
}

export async function provisionProjectDependencies(cwd: string): Promise<void> {
  try {
    // 1. Docker must be usable (a missing binary or dead daemon → 'failed').
    const docker = await runSetupCommand('docker', ['info'], cwd, undefined, { timeoutMs: 15_000 });
    if (docker.status !== 'ok') {
      log.info('provision', 'docker not usable — skipping dependency provisioning');
      return;
    }

    const pkg = await readPackageJson(cwd);
    let started = false;
    let generated: ServiceSpec[] = [];

    // 2. Compose-first: run what the project author already declared.
    const composeFile = await firstExisting(cwd, COMPOSE_FILES);
    if (composeFile) {
      log.info('provision', `compose found (${composeFile}) — docker compose up -d --wait`);
      const up = await runSetupCommand('docker', ['compose', 'up', '-d', '--wait'], cwd, undefined, {
        timeoutMs: 180_000,
      });
      // `--wait` returns non-zero if a service never goes healthy; treat
      // 'ok' as started, but also accept a plain up if --wait isn't honored.
      started = up.status === 'ok';
      if (!started) log.warn('provision', `compose up → ${up.status} (non-fatal)`);
    } else if (pkg) {
      // 3. Heuristic generation when the repo declares no compose.
      generated = detectServicesFromDeps(pkg);
      if (generated.length > 0) {
        const dir = path.join(cwd, '.codeam', 'provision');
        await fs.mkdir(dir, { recursive: true });
        const file = path.join(dir, 'compose.generated.yaml');
        await fs.writeFile(file, renderComposeYaml(generated));
        log.info(
          'provision',
          `no compose in repo — generated ${generated.map((s) => s.name).join('+')}`,
        );
        const up = await runSetupCommand(
          'docker',
          ['compose', '-f', file, 'up', '-d', '--wait'],
          cwd,
          undefined,
          { timeoutMs: 180_000 },
        );
        started = up.status === 'ok';
        if (!started) log.warn('provision', `generated compose up → ${up.status} (non-fatal)`);
      } else {
        log.info('provision', 'no compose + no known service deps — nothing to provision');
      }
    }

    // 4. `.env` — from the project's sample (preferred) or generated lines.
    await ensureEnvFile(cwd, generated);

    // 5. Best-effort migrations once services are up.
    if (started && pkg?.scripts) await runMigrationsIfPresent(cwd, pkg.scripts);

    log.info('provision', 'project dependency provisioning complete');
  } catch (err) {
    log.warn('provision', 'provisionProjectDependencies failed (non-fatal)', err);
  }
}
