/**
 * First-pair onboarding welcome.
 *
 * When a session is freshly paired, the agent proactively sends the user's
 * FIRST message — a short CodeAgent Mobile intro — right after the welcome
 * card, so the agent takes the initiative to invite the user to start.
 *
 * No new structure: this reuses the existing prompt→output flow. We send a
 * BACKGROUND prompt to the agent via `client.prompt()`; the instructions
 * themselves are never published as a user message (the CLI only publishes the
 * agent's streamed reply), so the app shows only the agent's onboarding text.
 *
 * Fires exactly once per paired session (a marker file under `~/.codeam`), so
 * reconnects / dormant-wakes don't re-welcome. Kill-switch:
 * `CODEAM_ONBOARDING_DISABLED`.
 */

import { execFileSync } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import type { StreamingChunkKind } from '@codeagent/shared';
import { log } from '../../services/logger';

/**
 * The turn-streaming surface from `StreamingState`. We drive a real turn so
 * mobile gets the `clear` + `new_turn` boundary (typing indicator), the
 * welcome text, and a final `done:true` — the SAME wire shape a real agent
 * reply produces, so the app renders it identically. The text is hardcoded
 * (NOT generated by the agent): a fixed informational welcome needs no model
 * round-trip, so it lands instantly and reliably regardless of agent/beads
 * startup timing.
 */
interface TurnStreaming {
  beginTurn(opts?: { clear?: boolean }): Promise<void>;
  append(delta: { chunkId: string; kind: StreamingChunkKind; delta: string }): void;
  closeAll(): Promise<void>;
}

/**
 * The conversation-anchor surface from `AcpHistory`. Recording the reply here
 * is what makes it survive a SessionDetail opened AFTER the turn completed —
 * the chat hydrates from this anchor, not from SSE catchup (which drops
 * historical text). `appendAgentInitiatedReply` records the reply with NO user
 * bubble, so our background instruction is never shown.
 */
interface WelcomeHistory {
  appendAgentInitiatedReply(text: string): void;
  flush(): Promise<void>;
}

/**
 * Seam for the once-per-session marker + kill-switch, so tests drive the guard
 * without touching the real `~/.codeam` or `process.env`.
 */
export const _onboardingSeam = {
  markerPath: (sessionId: string): string =>
    path.join(os.homedir(), '.codeam', 'welcomed', `${sessionId}.done`),
  exists: (p: string): boolean => fs.existsSync(p),
  write: (p: string): void => {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, '');
  },
  disabled: (): boolean => {
    const v = process.env.CODEAM_ONBOARDING_DISABLED;
    return !!v && v !== '0' && v.toLowerCase() !== 'false';
  },
  /**
   * The `origin` remote URL for `cwd`, or null when there's no git repo /
   * remote. Seam so tests drive `resolveRepoName` without a real checkout.
   */
  gitRemoteUrl: (cwd: string): string | null => {
    try {
      return execFileSync('git', ['-C', cwd, 'remote', 'get-url', 'origin'], {
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
        timeout: 2000,
      }).trim();
    } catch {
      return null;
    }
  },
};

/** True for a canonical 8-4-4-4-12 UUID (the codespace clone-dir name). */
function isUuid(s: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s);
}

/** Parse the repo name (no `.git`) out of an SSH or HTTPS git remote URL. */
function repoNameFromRemoteUrl(url: string): string | null {
  // git@github.com:owner/repo(.git)  |  https://github.com/owner/repo(.git)
  const m = url
    .trim()
    .replace(/\.git$/, '')
    .replace(/\/$/, '')
    .match(/[/:]([^/]+)\/([^/]+)$/);
  return m ? m[2] : null;
}

/**
 * Resolve a human-friendly repo name for the welcome CTA.
 *
 * `path.basename(cwd)` is WRONG in a CodeAgent codespace: the repo is cloned
 * into a directory named after the SESSION UUID, so the basename is a UUID
 * (e.g. `a2480d74-aaa4-…`) rather than the repo. Prefer the git `origin`
 * remote — it carries the real `owner/repo`. Fall back to the basename only
 * when it isn't a UUID, else a generic label.
 */
export function resolveRepoName(cwd: string): string {
  if (cwd) {
    const url = _onboardingSeam.gitRemoteUrl(cwd);
    if (url) {
      const name = repoNameFromRemoteUrl(url);
      if (name) return name;
    }
  }
  const base = path.basename(cwd || '');
  if (base && !isUuid(base)) return base;
  return 'this project';
}

/**
 * The hardcoded welcome message, published verbatim as the agent's first
 * turn. Static on purpose — it's purely informational, so there's no reason to
 * spend an agent round-trip generating it (which added latency and, worse,
 * sometimes never landed). Mobile-friendly markdown; the full https:// URLs
 * render as tappable links. Lightly tailored with the repo name.
 */
export function buildOnboardingWelcome(cwd: string): string {
  const repo = resolveRepoName(cwd);
  return [
    `Welcome to CodeAgent Mobile! 👋 You're now driving this agent from your phone — and it comes fully wired, zero setup:`,
    '',
    '- **Native repo context, persistent memory, and an issue tracker** — powered by Beads, out of the box.',
    '- **A full IDE** (Monaco) — edit code, live preview, and rich visual output, not just a file viewer.',
    '- **Smart Composer** — help crafting and structuring your prompts.',
    '- **Team Spaces** — share this session with your team, or hand it off to someone else.',
    '',
    'Found a bug or have feedback? Reach us at:',
    '- GitHub: https://github.com/edgar-durand/codeagent-mobile-clients/issues',
    '- Discord: https://discord.gg/ADMKwGAB',
    '',
    `Ready when you are — try **"explain ${repo}"** or **"what should I work on first?"**`,
  ].join('\n');
}

/**
 * Send the onboarding welcome once for a freshly paired session. Strictly
 * non-fatal: the turn streams back through the normal session/update →
 * publishOutput path AND is recorded into the conversation anchor so it shows
 * in chat even when SessionDetail is opened after the turn finishes. A failure
 * (or the kill-switch / an already-welcomed marker) just means no welcome this
 * run.
 *
 * Returns a promise that resolves when the welcome turn has FULLY closed (or
 * immediately when skipped). The caller awaits this before starting the
 * command relay: both the welcome turn and command turns drive the SAME shared
 * `StreamingState` buffer, so if the first `start_task` interleaves with an
 * in-flight welcome turn, the (instant, hardcoded) welcome wins the buffer and
 * the user's first prompt appears answered by the greeting (#339). Awaiting
 * here serializes the two without a turn mutex; the welcome has no model
 * round-trip so the added startup delay is a few publishes, not a turn.
 */
export async function maybeSendOnboardingWelcome(opts: {
  streaming: TurnStreaming;
  history: WelcomeHistory;
  sessionId: string;
  cwd: string;
}): Promise<void> {
  if (_onboardingSeam.disabled()) return;
  const marker = _onboardingSeam.markerPath(opts.sessionId);
  try {
    if (_onboardingSeam.exists(marker)) {
      // Already welcomed in a PRIOR run — this is a RESUME (supervisor
      // restart / auto-update / dormant-wake). Don't re-publish the welcome
      // live, but DO re-seed it into this run's (empty) history: the first
      // flush REPLACES the durable conversation with its in-memory list, so
      // without this a later flush — e.g. a failed/auth turn — would drop the
      // welcome banner the user still has on screen. Silent: no live publish,
      // no flush (the next real turn's flush carries it). Best-effort.
      try {
        opts.history.appendAgentInitiatedReply(buildOnboardingWelcome(opts.cwd));
      } catch {
        /* non-fatal — worst case the welcome is absent from a resumed flush */
      }
      return;
    }
    _onboardingSeam.write(marker);
  } catch (err) {
    // Can't read/write the marker — skip rather than risk re-welcoming on a
    // loop. (A transient FS error is rarer + less annoying than a double send.)
    log.trace('acpRunner', `onboarding marker check failed: ${(err as Error).message}`);
    return;
  }
  log.info('acpRunner', `sending first-pair onboarding welcome for session=${opts.sessionId.slice(0, 8)}`);
  // Run the welcome turn to completion; swallow errors (non-fatal). The caller
  // awaits this so the turn fully closes before the relay can begin a command
  // turn on the shared StreamingState (#339).
  try {
    await runOnboardingTurn(opts);
  } catch (err: unknown) {
    log.warn(
      'acpRunner',
      `onboarding welcome turn failed (non-fatal): ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/**
 * Publish the hardcoded welcome as a real turn and persist it.
 *
 * Mirrors the runner's normal turn shape — `beginTurn()` (clear + new_turn →
 * "Agent is typing…"), `append()` the welcome text, `closeAll()` (one
 * `done:true`) — then records it into the conversation anchor WITHOUT a user
 * prompt. The anchor is what mobile's chat hydrates from on open, so this is
 * what makes the welcome appear when the user navigates in after it landed.
 * No `client.prompt()` — the text is static, so there's no agent round-trip.
 */
async function runOnboardingTurn(opts: {
  streaming: TurnStreaming;
  history: WelcomeHistory;
  cwd: string;
}): Promise<void> {
  const { streaming, history, cwd } = opts;
  const welcome = buildOnboardingWelcome(cwd);
  // clear: false — keep the agent_banner card published moments earlier
  // (the welcome turn's clear would otherwise flush it from the backend
  // output buffer that SSE catchup replays). This is the first turn, so
  // there's nothing else to clear.
  await streaming.beginTurn({ clear: false });
  try {
    // Single text chunk — `append` publishes the chat bubble + streaming-chunk
    // feed; `closeAll` flips it to done. Fixed chunkId: one chunk per welcome.
    streaming.append({ chunkId: 'onboarding-welcome', kind: 'text', delta: welcome });
    await streaming.closeAll();
    history.appendAgentInitiatedReply(welcome);
    await history.flush();
  } catch (err) {
    // Best-effort finalize so the chat doesn't sit on "Agent is typing…".
    await streaming.closeAll().catch(() => undefined);
    throw err;
  }
}
